#!/usr/bin/env python3

import numpy as np
import argparse

'''将EMAN2的输出角度保存为lst文件'''
parser = argparse.ArgumentParser(description='Convert EMAN2 text file to lst file')
parser.add_argument('input', metavar='Input_file', help='The text file generated by e2project3d.py')
parser.add_argument('-p', metavar='--parts', dest='parts', default='1', type=int, help='The number of splitting files. Default: 1')
args = parser.parse_args()

input_file = args.input
file_name = input_file.split('.')[0]

with open(input_file, 'r') as file:
    lines = file.readlines()[3:-1]

psi_angles = []
theta_angles = []
phi_angles = []

# 根据需求将欧拉角分组
if p == 1:
    for i in lines:
        psi = np.float32(i.split('\t')[1]) # azimuthal
        theta = np.float32(i.split('\t')[2]) # altitude
        phi = np.float32((i.split('\t')[3]).split('\\')[0]) # psi
        psi_angles.append(psi)
        theta_angles.append(theta)
        phi_angles.append(phi)
    data = np.stack([theta_angles, psi_angles, phi_angles], axis=1)
    np.savetxt(f'{file_name}.lst', data, delimiter='\t', fmt='%3.4f')
elif p >= 2:
    p_n = round(len(lines)/p)
    for i in range(p):
        psi_angles = []
        theta_angles = []
        phi_angles = []
        if i == p-1:
            start = i*p_n
            split_lines = lines[start:]
        else:
            start = i*p_n
            end = (i+1)*p_n
            split_lines = lines[start:end]
        for j in split_lines:
            psi = np.float32(i.split('\t')[1]) # azimuthal
            theta = np.float32(i.split('\t')[2]) # altitude
            phi = np.float32((i.split('\t')[3]).split('\\')[0]) # psi
            psi_angles.append(psi)
            theta_angles.append(theta)
            phi_angles.append(phi)
        data = np.stack([theta_angles, psi_angles, phi_angles], axis=1)
        with open(f'{file_name}_part{i+1}.lst', 'w') as f:
            np.savetxt(f, data, delimiter='\t', fmt='%3.4f')