#!/usr/bin/env python3

import argparse
import os

from postprocess_lst import postprocess_lst
from postprocess_star import postprocess_star

def main():
    """通过颗粒的坐标和欧拉角距离将重复颗粒排除"""
    inlst, num, center, euler_thres, scale, apix, mdir, output, score_threshold, cpu =  parse_command_line()

    if mdir[-1] == '/':
        mdir = mdir[:-1]

    file_extension = os.path.splitext(inlst)[-1]
    if file_extension == '.star':
        postprocess_star(inlst, num, center, euler_thres, scale, output, score_threshold, cpu)
    elif file_extension == '.lst':
        postprocess_lst(inlst, num, center, euler_thres, scale, apix, mdir, output, score_threshold, cpu)
    

def parse_command_line():
    #提取输入的各个参数
    #usage = "%prog <Detection file> <Number of windows> <Center threshold> <Euler threshold> <Output>"
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter, 
        description='''isSPA_1.1.3 by Zhang Lab at Institute of Biophysics, Chinese Academy of Sciences\nRemove duplicated particles and prepare the STAR file'''
        )
    parser.add_argument('input', metavar='Input_file', help='The .lst file generated by isSPA from target detection')
    parser.add_argument('num', metavar='N', type=int, help='Number of micrographs')
    parser.add_argument('center', metavar='d', type=float, help='The largest distance (pixel) between duplicated points')
    parser.add_argument('euler', metavar='Angle_threshold', type=float, help='The largest angle between two Euler angles')
    parser.add_argument('scale', metavar='Scale', type=float, help='The binning factor used during target detection')
    parser.add_argument('pixel', metavar='Pixel_size', type=float, help='The original pixel size (angstrom) of the original micrograph')
    parser.add_argument('dir', metavar='Micrograph_dir', help='The directory of the original micrographs')
    parser.add_argument('score', metavar='Score_threshold', type=float, help='The score threshold used to filter particles')
    parser.add_argument('-o', metavar='--output', dest='output', default='_merge.star', help='The output file. Default name: {input}_merge.star')
    parser.add_argument('-cpu', metavar='--cpu_num', dest='cpu', type=int, default=0, help='The number of available CPU. Default: half')

    args = parser.parse_args()

    inlst = args.input
    num = args.num
    center = args.center
    euler_thres = args.euler
    scale = args.scale
    apix = args.pixel
    mdir = args.dir
    output = args.output
    score_threshold = args.score
    cpu = args.cpu

    return inlst, num, center, euler_thres, scale, apix, mdir, output, score_threshold, cpu

if __name__== "__main__":
    main()
