#!/usr/bin/env python3

import argparse
import os
import subprocess

import numpy as np

from read_line_format import read_line_format
from write_lst import write_lst

"""
缩小所有照片的尺寸并放到一个文件夹中，将micrograph_ctf.star转换为micrograph_ctf.lst
"""

parser = argparse.ArgumentParser(description='This program will bin all the micrographs and put them in a directory. Then it will convert .star file to .lst file')
parser.add_argument('dir', metavar='Micrograph_directory', help='The directory containing micrographs')
parser.add_argument('t', metavar='Template_map', help='The template map file')
parser.add_argument('bin', metavar='Bin_factor', type=float, help='The bin factor you would like to use')
parser.add_argument('pixel', metavar='Pixel_size', type=float, help='The original pixel size')
parser.add_argument('star', metavar='STAR_file', help='The .star file generated by RELION after CTF estimation')
parser.add_argument('-o', metavar='--output', dest='output', default='micrograph_ctf.lst', help='The output file. Default: micrograph_ctf.lst')
parser.add_argument('-s', metavar='--suffix', dest='suffix', default='.mrc', help='The suffix of micrographs. Default: mrc')

args = parser.parse_args()

input_dir = args.dir
template = args.t
bin_factor = args.bin
pixel = args.pixel
instar = args.star
lst = args.output
suffix = args.suffix

pixel_b = np.round(pixel * bin_factor, 6)

if input_dir[-1] == '/':
    input_dir = input_dir[:-1]

file_list = []
for file in os.listdir(input_dir):
    if file.endswith(suffix):
        file_list.append(file)

if bin_factor > 1:
    lst_parts = lst.split('ctf.lst')[0]
    lst = f"{lst_parts}bin{bin_factor}_ctf.lst"
    template_name_parts = template.split('.mrc')[0]
    template_new_name = f"{template_name_parts}_pz{pixel_b}.mrc"
    p1 = subprocess.Popen(f'relion_image_handler --i {template} --rescale_angpix {pixel_b} --o {template_new_name} >> preprocess.log', shell=True)
    # 创建文件夹
    if os.path.exists(f'{input_dir}/bin{bin_factor}') == False:
        os.mkdir(f'{input_dir}/bin{bin_factor}')
    for j,i in enumerate(file_list):
        name = i.split('.')[0]
        p = subprocess.Popen(f'relion_image_handler --i {input_dir}/{i} --o {input_dir}/bin{bin_factor}/{name}_bin{bin_factor}.mrc --angpix {pixel} --rescale_angpix {pixel_b} >> preprocess.log', shell=True)
        if j != 0:
            if j % 12 == 0:
                p.wait()
                print(f' {j} micrographs are binned!\n')
        if j == len(file_list)-1:
            p.wait()
            p1.wait()
            print(f' All micrographs are binned! The pixel size is {pixel_b} Å.\n')
                #time.sleep(5)

fnum = 0 # image number in new file

star_format = read_line_format(instar)
if star_format[-1] == 0:
    spliter = " "
elif star_format[-1] == 1:
    spliter = "\t"
with open(instar, 'r') as f:
    lines = f.readlines()

if len(star_format) == 3:
    write_lst(lines, star_format, lst, 0, spliter, fnum, bin_factor)
else:
    write_lst(lines, star_format, lst, 1, spliter, fnum, bin_factor)

print(" Preprocessing is finished!\n")